# Example HTTP requests to test APIs

# GET request to fetch all items
GET http://localhost:3000/events


### Get request to fetch a single item by ID
GET http://localhost:3000/events/1 
###

# POST request to create a new item
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "Sample Item sdsdfsdf",
    "description": "This is a sample item.",
    "date": "2023-10-01T00:00:00Z",
    "location": "Sample Location",
    "isActive": true
}

###

# PUT request to update an existing item
PATCH  http://localhost:3000/events/1
Content-Type: application/json

{
    "name": "Updated Item updated"
}

###

# DELETE request to delete an item
DELETE http://localhost:3000/events/1
Content-Type: application/json

### create user
POST http://localhost:3000/users/loginRegister
Content-Type: application/json

{
    "email": "baha@innovationfactory.biz"
}

### verify user
POST http://localhost:3000/users/verify
Content-Type: application/json

{
    "email": "baha@innovationfactory.biz",
    "otp": "743737"
}

### delete user
DELETE  http://localhost:3000/users/6


### logout
POST http://localhost:3000/users/logout
Content-Type: application/json