### get all users
GET  http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI4LCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaXNWZXJpZmllZCI6dHJ1ZSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTk3MzcxNzEsImV4cCI6MTc1OTc0MDc3MX0.MDKja-THbVhhBSNDAVEvKeMJt3fNsjCaoKNHZwWfI-s


### get current user
GET http://localhost:3000/admin/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaXNWZXJpZmllZCI6dHJ1ZSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNzU5OTIzNzI4LCJleHAiOjE3NTk5MjczMjh9.a1-qY8mqJy0yvn7Huokdu0z1EojlX1s_rvwtB0K_c9E


### get all users
GET http://localhost:3000/admin/users
### get user by id
GET http://localhost:3000/admin/users/15

### Approve admin
POST http://localhost:3000/admin/users/15/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaXNWZXJpZmllZCI6dHJ1ZSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNzU5OTIzNzI4LCJleHAiOjE3NTk5MjczMjh9.a1-qY8mqJy0yvn7Huokdu0z1EojlX1s_rvwtB0K_c9E

### delete user
DELETE  http://localhost:3000/admin/users/10