### get all users
GET  http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6ImJhaGFhLmJha3JpMTk5NUBnbWFpbC5jb20iLCJpc1ZlcmlmaWVkIjp0cnVlLCJyb2xlIjoidXNlciIsImlhdCI6MTc2MDAwNzE0MCwiZXhwIjoxNzYwNjExOTQwfQ.Pr1NneSjYM7n1DeTG5B8x-J1SZeJR-3MdCL7qwGvj7M


### get current user
GET http://localhost:3000/admin/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpc1ZlcmlmaWVkIjp0cnVlLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJpYXQiOjE3NjA5NDUzNTcsImV4cCI6MTc2MTU1MDE1N30.SlmbnBzbrj6IG8PuXsTKHDIsXjrBTQidLlCZ_UDUoWM

### get all users
GET http://localhost:3000/admin/users?page=2&perPage=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaXNWZXJpZmllZCI6dHJ1ZSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNzYwMDE3NTUxLCJleHAiOjE3NjA2MjIzNTF9.2iPnMquqTGOtBTro9Uty0wrhBs5DenTL4wZ4m_0XqJQ

### get user by id
GET http://localhost:3000/admin/users/17

### Approve admin
POST http://localhost:3000/admin/users/14/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaXNWZXJpZmllZCI6dHJ1ZSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNzYwMDE3NTUxLCJleHAiOjE3NjA2MjIzNTF9.2iPnMquqTGOtBTro9Uty0wrhBs5DenTL4wZ4m_0XqJQ

### delete user
DELETE  http://localhost:3000/admin/users/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaXNWZXJpZmllZCI6dHJ1ZSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNzYwMDE3NTUxLCJleHAiOjE3NjA2MjIzNTF9.2iPnMquqTGOtBTro9Uty0wrhBs5DenTL4wZ4m_0XqJQ
