### get all users
GET  http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI4LCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaXNWZXJpZmllZCI6dHJ1ZSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTk3MzcxNzEsImV4cCI6MTc1OTc0MDc3MX0.MDKja-THbVhhBSNDAVEvKeMJt3fNsjCaoKNHZwWfI-s


### get current user
GET http://localhost:3000/admin/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6InRlc3RiYmJAaW5ub3ZhdGlvbmZhY3RvcnkuYml6IiwiaXNWZXJpZmllZCI6dHJ1ZSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNzQ5NjQ1NTkzLCJleHAiOjE3NTA5NDE1OTN9.CNtypEWDTdqPxGJrqJ1z-HHHKJlNTT55PZR0zJ1Jz2k


### get all users
GET http://localhost:3000/admin/users
### get user by id
GET http://localhost:3000/admin/users/15

### Approve admin
POST http://localhost:3000/admin/users/25/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaXNWZXJpZmllZCI6dHJ1ZSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNzU4MTgyMjU3LCJleHAiOjE3NTgxODU4NTd9.Yf09cJtQyWXUDnsZtsD3gF4YUE4vzj7nLGZiXfqX-ns

### delete user
DELETE  http://localhost:3000/admin/users/10