### login register user
POST http://localhost:3000/auth/loginRegister
Content-Type: application/json

{
    "email": "testtbbb@innovationfactory.biz"
}

### verify user
POST http://localhost:3000/auth/verify
Content-Type: application/json

{
    "email": "testrrr@innovationfactory.biz",  
    "otp": "654681"
}


### login admin
POST http://localhost:3000/admin/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com"
}

### register admin
POST http://localhost:3000/admin/auth/register
Content-Type: application/json

{
    "email": "testadmin5@innovationfactory.biz",
    "firstname": "Bahaa",
    "lastname": "Bakri",
    "phone": "+971524371041"
}

### verify admin
POST http://localhost:3000/admin/auth/verify
Content-Type: application/json

{
    "email": "test@gmail.com",
    "otp": "276591"
}


POST http://localhost:3000/auth/google-login
Content-Type: application/json

{
    "token": "xxx",
}