### delete user
DELETE  http://localhost:3000/users/10


### get all users
POST http://localhost:3000/users/me


### get current user
POST http://localhost:3000/admin/users/me

### get user by id
GET http://localhost:3000/admin/users/15