# Example HTTP requests to test APIs

# GET request to fetch all items
GET http://localhost:3000/events?page=2&perPage=10


### Get request to fetch a single item by ID
GET http://localhost:3000/events/40
###

# POST request to create a new item
POST http://localhost:3000/admin/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpc1ZlcmlmaWVkIjp0cnVlLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJpYXQiOjE3NjA1MzQ5NjgsImV4cCI6MTc2MTEzOTc2OH0.1FKq0QgIGnETS054IucUvt3_gFNXrB-nt-OssgQ_ZuQ

{
    "name": "test with images 40",
    "description": "This is a sample item.",
    "date": "2026-10-01T00:00:00Z",
    "location": "Sample Location",
    "lat": 40.7128,
    "lng": -74.0060,
    "imagesIds": ["1"],
    "capacity": 100
}

###

# PUT request to update an existing item
PATCH  http://localhost:3000/events/40
Content-Type: application/json

{
    "name": "Updated Item updated"
}

###

# DELETE request to delete an item
DELETE http://localhost:3000/admin/events/13
Content-Type: application/json


### Patch request to approve an event
PATCH http://localhost:3000/admin/events/2/approve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpc1ZlcmlmaWVkIjp0cnVlLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJpYXQiOjE3NjA1MzQ5NjgsImV4cCI6MTc2MTEzOTc2OH0.1FKq0QgIGnETS054IucUvt3_gFNXrB-nt-OssgQ_ZuQ

{
    "approved": true
}

### join event
POST http://localhost:3000/ticket/2/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGVzdHVzZXJAZ21haWwuY29tIiwiaXNWZXJpZmllZCI6dHJ1ZSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjA1MzU3MzAsImV4cCI6MTc2MTE0MDUzMH0.O4VuomVrxKWuUW8MadMCR0Fx2qyXuTjMMXtNtU-1zJs

{
    "quantity": 2,
    "price": 10,
    "currency": "USD"
}