# Example HTTP requests to test APIs

# GET request to fetch all items
GET http://localhost:3000/events?page=2&perPage=10


### Get request to fetch a single item by ID
GET http://localhost:3000/events/35
###

# POST request to create a new item
POST http://localhost:3000/admin/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIwLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaXNWZXJpZmllZCI6dHJ1ZSwicm9sZSI6InN1cGVyX2FkbWluIiwiaWF0IjoxNzU5OTIzNzI4LCJleHAiOjE3NTk5MjczMjh9.a1-qY8mqJy0yvn7Huokdu0z1EojlX1s_rvwtB0K_c9E

{
    "name": "test with images 38",
    "description": "This is a sample item.",
    "date": "2023-10-01T00:00:00Z",
    "location": "Sample Location",
    "lat": 40.7128,
    "lng": -74.0060,
    "imagesIds": ["22"]
}

###

# PUT request to update an existing item
PATCH  http://localhost:3000/events/13
Content-Type: application/json

{
    "name": "Updated Item updated"
}

###

# DELETE request to delete an item
DELETE http://localhost:3000/admin/events/13
Content-Type: application/json


### Patch request to approve an event
PATCH http://localhost:3000/admin/events/3/approve
Content-Type: application/json

{
    "approved": true
}