### login register user
POST http://localhost:3000/auth/loginRegister
Content-Type: application/json

{
    "email": "testbbb@innovationfactory.biz"
}

### verify user
POST http://localhost:3000/auth/verify
Content-Type: application/json

{
    "email": "testbbb@innovationfactory.biz",
    "otp": "923198"
}


### login register admin
POST http://localhost:3000/admin/auth/loginRegister
Content-Type: application/json

{
    "email": "testbbb@innovationfactory.biz"
}

### verify user
POST http://localhost:3000/admin/auth/verify
Content-Type: application/json

{
    "email": "testbbb@innovationfactory.biz",
    "otp": "161829"
}