### login register user
POST http://localhost:3000/admin/auth/loginRegister
Content-Type: application/json

{
    "email": "testbbb@innovationfactory.biz"
}

### verify user
POST http://localhost:3000/admin/auth/verify
Content-Type: application/json

{
    "email": "testbbb@innovationfactory.biz",
    "otp": "228271"
}

### logout
POST http://localhost:3000/admin/auth/logout
Content-Type: application/json