### login register user
POST http://localhost:3000/auth/loginRegister
Content-Type: application/json

{
    "email": "testtbbb@innovationfactory.biz"
}

### verify user
POST http://localhost:3000/auth/verify
Content-Type: application/json

{
    "email": "testtbbb@innovationfactory.biz",
    "otp": "690464"
}


### login admin
POST http://localhost:3000/admin/auth/login
Content-Type: application/json

{
    "email": "testadmin2@innovationfactory.biz"
}

### register admin
POST http://localhost:3000/admin/auth/register
Content-Type: application/json

{
    "email": "testadmin5@innovationfactory.biz",
    "firstname": "Bahaa",
    "lastname": "Bakri",
    "phone": "+971524371041"
}

### verify admin
POST http://localhost:3000/admin/auth/verify
Content-Type: application/json

{
    "email": "testadmin5@innovationfactory.biz",
    "otp": "977176"
}